version: '3.9'

volumes:
  app_logs:

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - app_logs:/var/log
    depends_on:
      - tempo
      - loki

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200"
      - "4317:4317"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    # kalau nggak punya custom config, cukup gini:
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # hapus kalau folder provisioning belum ada
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - app_logs:/var/log
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
