server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: service-1
  static_configs:
  - targets:
      - localhost
    labels:
      job: service-1
      __path__: /var/log/app.log
- job_name: service-2
  static_configs:
  - targets:
      - localhost
    labels:
      job: service-2
      __path__: /var/log/app2.log
