apiVersion: 1
datasources:

  - name: DS_PROMETHEUS
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: DS_LOKI
    uid: loki
    type: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([a-f0-9]+)"'
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlLabel: View trace

  - name: DS_TEMPO
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'
      tracesToLogs:
        datasourceUid: 'loki'
        # tags: ['job', 'instance', 'pod', 'namespace']
        # mappedTags: [{ key: 'service.name', value: 'service' }]
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: prometheus