apiVersion: 1
datasources:

  - name: DS_PROMETHEUS
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: DS_LOKI
    uid: loki
    type: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([a-f0-9]+)"'
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlLabel: View trace

  - name: DS_TEMPO
    uid: tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        mappedTags:
          - service.name
        mapTagNamesEnabled: true
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        customQuery: true
        query: '{job="app-logs"} |= "$${__trace.traceID}"'
      serviceMap:
        datasourceUid: prometheus