{
 "title": "Fiber-App Observability",
 "tags": [
  "observability",
  "fiber"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate (Fiber)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{job=\"fiber-app\"}[5m])"
    }
   ]
  },
  {
   "title": "p95 Latency (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"fiber-app\"}[5m]))"
    }
   ]
  },
  {
   "title": "Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"service-1\"}"
    }
   ]
  },
  {
   "title": "5xx Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{job=\"fiber-app\",status=~\"5..\"}[5m])"
    }
   ]
  },
  {
   "title": "Recent Traces (Tempo)",
   "type": "table",
   "gridPos": { "x": 12, "y": 16, "h": 8, "w": 12 },
   "targets": [
    {
     "limit": 20,
     "tableType": "traces",
     "metricsQueryType": "range",
     "filters": [
      { "id": "c5c6dd78", "operator": "=", "scope": "span" }
     ]
    }
   ]
  }
 ]
}